import { StyleSheet } from 'react-native';

export const HEADER_CONTENT_HEIGHT = 56;
export const HEADER_BOTTOM_GAP = 12;
export const WEB_MOBILE_SAFE_TOP = 44;
export const FONT_SERIF = 'PlayfairDisplay_700Bold';
export const FONT_SANS = 'Inter_400Regular';
export const FONT_SANS_SEMIBOLD = 'Inter_600SemiBold';
export const FONT_SANS_BOLD = 'Inter_700Bold';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fffdf9',
  },
  appShell: {
    flex: 1,
    backgroundColor: '#fffdf9',
  },
  header: {
    position: 'relative',
    zIndex: 50,
    paddingHorizontal: 20,
    paddingBottom: HEADER_BOTTOM_GAP,
    minHeight: HEADER_CONTENT_HEIGHT,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerTitle: {
    color: '#163f86',
    fontSize: 28,
    fontFamily: FONT_SERIF,
    letterSpacing: -0.4,
  },
  headerBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoMark: {
    width: 38,
    height: 34,
    position: 'relative',
  },
  logoSheet: {
    position: 'absolute',
    width: 24,
    height: 28,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#1f55ab',
    backgroundColor: '#fffefc',
  },
  logoSheetBack: {
    left: 1,
    top: 4,
    opacity: 0.45,
    transform: [{ rotate: '-8deg' }],
  },
  logoSheetMiddle: {
    left: 8,
    top: 2,
    opacity: 0.72,
    transform: [{ rotate: '-2deg' }],
  },
  logoSheetFront: {
    left: 13,
    top: 0,
    paddingHorizontal: 4,
    paddingTop: 4,
  },
  logoRule: {
    width: 10,
    height: 2.5,
    borderRadius: 999,
    backgroundColor: '#1f55ab',
  },
  logoLineShort: {
    marginTop: 4,
    width: 8,
    height: 2,
    borderRadius: 999,
    backgroundColor: '#86a8dd',
  },
  logoLineLong: {
    marginTop: 3,
    width: 12,
    height: 2,
    borderRadius: 999,
    backgroundColor: '#86a8dd',
  },
  logoSignal: {
    position: 'absolute',
    right: -3,
    top: -3,
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#e85b4f',
    borderWidth: 1.5,
    borderColor: '#fffdf9',
  },
  headerActions: {
    alignItems: 'flex-end',
    position: 'relative',
  },
  menuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
  },
  menuButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: '#f4f8ff',
    borderWidth: 1,
    borderColor: '#dce8fb',
  },
  menuButtonText: {
    color: '#2158b1',
    fontFamily: FONT_SANS_BOLD,
    fontSize: 13,
  },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fbfdff',
    borderWidth: 1,
    borderColor: '#dbe7fb',
  },
  iconButtonText: {
    color: '#2158b1',
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '600',
  },
  topicActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  scopeIconButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fbfdff',
    borderWidth: 1,
    borderColor: '#dbe7fb',
  },
  scopeIconGlyph: {
    width: 14,
    gap: 3,
  },
  scopeIconLineShort: {
    width: 9,
    height: 2,
    borderRadius: 999,
    backgroundColor: '#2b61b7',
  },
  scopeIconLineLong: {
    width: 14,
    height: 2,
    borderRadius: 999,
    backgroundColor: '#e85b4f',
  },
  menuPanel: {
    position: 'absolute',
    top: 58,
    right: 0,
    minWidth: 148,
    padding: 8,
    borderRadius: 10,
    backgroundColor: '#fffefc',
    borderWidth: 1,
    borderColor: '#e2eaf8',
    shadowColor: '#2b5fad',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 5,
    zIndex: 200,
  },
  menuItem: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 8,
  },
  menuItemText: {
    color: '#255fbe',
    fontWeight: '600',
  },
  menuItemTextActive: {
    color: '#ea5445',
  },
  content: {
    flex: 1,
    zIndex: 1,
  },
  feedWrapper: {
    flex: 1,
  },
  learnProgressInline: {
    marginHorizontal: 18,
    marginBottom: 6,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#f7faff',
    borderWidth: 1,
    borderColor: '#e1eaf8',
  },
  learnProgressInlineText: {
    color: '#5d7694',
    fontSize: 12,
    lineHeight: 16,
    fontFamily: FONT_SANS_SEMIBOLD,
  },
  page: {
    paddingHorizontal: 0,
    paddingBottom: 0,
    overflow: 'hidden',
  },
  card: {
    flex: 1,
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 0,
    paddingHorizontal: 24,
    paddingVertical: 22,
    borderTopWidth: 1,
    borderTopColor: '#e1ebfb',
  },
  cardScroll: {
    flex: 1,
  },
  cardScrollContent: {
    paddingBottom: 10,
  },
  newsCard: {
    backgroundColor: '#fffdf9',
  },
  topicMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badge: {
    backgroundColor: '#eef5ff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  badgeText: {
    color: '#2b61b7',
    fontSize: 11,
    fontFamily: FONT_SANS_BOLD,
  },
  readTime: {
    color: '#6b86ad',
    fontSize: 12,
    fontFamily: FONT_SANS,
  },
  pageCountRow: {
    marginTop: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  kickerText: {
    color: '#cf5a47',
    fontSize: 11,
    fontFamily: FONT_SANS_BOLD,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  topicTitle: {
    marginTop: 8,
    color: '#173f7b',
    fontSize: 20,
    lineHeight: 26,
    fontFamily: FONT_SERIF,
    letterSpacing: -0.3,
  },
  topicSummary: {
    marginTop: 10,
    color: '#476486',
    fontSize: 16,
    lineHeight: 25,
    fontFamily: FONT_SANS,
  },
  pointList: {
    marginTop: 16,
    gap: 10,
  },
  pointRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'flex-start',
  },
  pointDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    marginTop: 7,
    backgroundColor: '#e85b4f',
  },
  pointText: {
    flex: 1,
    color: '#58718f',
    fontSize: 14,
    lineHeight: 22,
    fontFamily: FONT_SANS,
  },
  takeawayPreview: {
    marginTop: 18,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#e8eef8',
    gap: 8,
  },
  takeawayPreviewLabel: {
    color: '#cf5a47',
    fontSize: 11,
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    fontFamily: FONT_SANS_BOLD,
  },
  takeawayPreviewText: {
    color: '#516d8f',
    fontSize: 14,
    lineHeight: 22,
    fontFamily: FONT_SANS,
  },
  primaryButton: {
    paddingHorizontal: 18,
    paddingVertical: 15,
    backgroundColor: '#2b61b7',
    borderRadius: 18,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontFamily: FONT_SANS_BOLD,
  },
  secondaryButton: {
    paddingHorizontal: 18,
    paddingVertical: 15,
    backgroundColor: '#fffefc',
    borderWidth: 1,
    borderColor: '#dbe7fb',
    borderRadius: 18,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#2158b1',
    fontSize: 15,
    fontFamily: FONT_SANS_BOLD,
  },
  disabledButton: {
    opacity: 0.48,
  },
  tagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 20,
  },
  tagPill: {
    backgroundColor: '#f3f7ff',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  tagText: {
    color: '#2c60b1',
    fontSize: 12,
    fontFamily: FONT_SANS_SEMIBOLD,
  },
  sourcePanel: {
    marginTop: 22,
    padding: 16,
    backgroundColor: '#f7faff',
    borderRadius: 0,
    borderLeftWidth: 3,
    borderLeftColor: '#2d66c2',
  },
  sourceLabel: {
    color: '#6883a8',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontFamily: FONT_SANS_BOLD,
  },
  sourceName: {
    marginTop: 8,
    color: '#193f79',
    fontSize: 16,
    fontFamily: FONT_SANS_SEMIBOLD,
  },
  settingsContainer: {
    flex: 1,
    paddingHorizontal: 18,
    paddingBottom: 18,
    gap: 16,
  },
  libraryContainer: {
    paddingHorizontal: 18,
    paddingBottom: 24,
    gap: 16,
  },
  librarySearchShell: {
    borderWidth: 1,
    borderColor: '#e1eaf8',
    backgroundColor: '#fffefc',
    paddingHorizontal: 14,
  },
  librarySearchInput: {
    height: 48,
    color: '#173f7b',
    fontSize: 15,
    fontFamily: FONT_SANS,
  },
  libraryOverviewCard: {
    padding: 18,
    borderRadius: 0,
    backgroundColor: '#fffefc',
    borderWidth: 1,
    borderColor: '#e1eaf8',
    gap: 10,
  },
  libraryOverviewCardActive: {
    borderColor: '#2d66c2',
    backgroundColor: '#f8fbff',
  },
  libraryBookCard: {
    padding: 18,
    borderRadius: 0,
    backgroundColor: '#fffefc',
    borderWidth: 1,
    borderColor: '#e1eaf8',
    gap: 14,
  },
  libraryBookHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  libraryBookText: {
    flex: 1,
    gap: 6,
  },
  libraryBookTitle: {
    color: '#173f7b',
    fontSize: 22,
    lineHeight: 28,
    fontFamily: FONT_SERIF,
  },
  libraryBookMeta: {
    color: '#6a809f',
    fontSize: 13,
    lineHeight: 20,
    fontFamily: FONT_SANS,
  },
  libraryBookBody: {
    color: '#58718f',
    fontSize: 15,
    lineHeight: 23,
    fontFamily: FONT_SANS,
  },
  librarySelectButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#f4f8ff',
    borderWidth: 1,
    borderColor: '#dce8fb',
  },
  librarySelectButtonActive: {
    backgroundColor: '#2d66c2',
    borderColor: '#2d66c2',
  },
  librarySelectButtonText: {
    color: '#2158b1',
    fontSize: 13,
    fontFamily: FONT_SANS_BOLD,
  },
  librarySelectButtonTextActive: {
    color: '#ffffff',
  },
  chapterList: {
    gap: 10,
  },
  chapterBlock: {
    gap: 8,
  },
  chapterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#e6edf8',
    backgroundColor: '#fffdf9',
  },
  chapterRowActive: {
    borderColor: '#2d66c2',
    backgroundColor: '#f7faff',
  },
  chapterNumber: {
    width: 28,
    height: 28,
    borderRadius: 999,
    backgroundColor: '#eef5ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chapterNumberText: {
    color: '#2b61b7',
    fontSize: 13,
    fontFamily: FONT_SANS_BOLD,
  },
  chapterText: {
    flex: 1,
    gap: 4,
  },
  chapterJumpText: {
    color: '#2158b1',
    fontSize: 13,
    fontFamily: FONT_SANS_BOLD,
  },
  chapterTopicList: {
    marginLeft: 40,
    gap: 8,
  },
  chapterTopicRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderLeftWidth: 2,
    borderLeftColor: '#e3eaf7',
    backgroundColor: '#fffdf9',
  },
  chapterTopicRowFocused: {
    borderLeftColor: '#e85b4f',
    backgroundColor: '#fff7f4',
  },
  chapterTopicTitle: {
    color: '#58718f',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: FONT_SANS,
  },
  chapterTopicTitleFocused: {
    color: '#173f7b',
    fontFamily: FONT_SANS_SEMIBOLD,
  },
  chapterTitle: {
    color: '#173f7b',
    fontSize: 15,
    lineHeight: 21,
    fontFamily: FONT_SANS_SEMIBOLD,
  },
  chapterMeta: {
    color: '#6a809f',
    fontSize: 13,
    lineHeight: 19,
    fontFamily: FONT_SANS,
  },
  libraryEmptyState: {
    padding: 18,
    borderWidth: 1,
    borderColor: '#e1eaf8',
    backgroundColor: '#fffefc',
    gap: 8,
  },
  settingsTitle: {
    color: '#173f7b',
    fontSize: 28,
    fontFamily: FONT_SERIF,
    marginTop: 6,
  },
  settingsBody: {
    color: '#58718f',
    fontSize: 16,
    lineHeight: 24,
    fontFamily: FONT_SANS,
  },
  segmentedControl: {
    flexDirection: 'row',
    padding: 6,
    borderRadius: 10,
    backgroundColor: '#f7faff',
    gap: 8,
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
  },
  segmentButtonActive: {
    backgroundColor: '#2d66c2',
  },
  segmentButtonText: {
    color: '#6883a8',
    fontFamily: FONT_SANS_BOLD,
  },
  segmentButtonTextActive: {
    color: '#ffffff',
  },
  settingsCard: {
    padding: 18,
    borderRadius: 0,
    backgroundColor: '#fffefc',
    borderWidth: 1,
    borderColor: '#e1eaf8',
    gap: 10,
  },
  settingsCardTitle: {
    color: '#6b86ad',
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontFamily: FONT_SANS_BOLD,
  },
  settingsCardValue: {
    color: '#173f7b',
    fontSize: 22,
    fontFamily: FONT_SANS_SEMIBOLD,
  },
  settingsHint: {
    color: '#6a809f',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: FONT_SANS,
  },
  healthActionRow: {
    gap: 10,
  },
  healthErrorText: {
    color: '#cf4339',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: FONT_SANS,
  },
  healthMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  healthMetricTile: {
    width: '48%',
    minHeight: 92,
    padding: 14,
    backgroundColor: '#f7faff',
    borderWidth: 1,
    borderColor: '#e1eaf8',
    justifyContent: 'space-between',
  },
  healthMetricLabel: {
    color: '#6b86ad',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontFamily: FONT_SANS_BOLD,
  },
  healthMetricValue: {
    marginTop: 10,
    color: '#173f7b',
    fontSize: 18,
    lineHeight: 24,
    fontFamily: FONT_SANS_SEMIBOLD,
  },
  celebrationOverlay: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 28,
    alignItems: 'center',
  },
  celebrationToast: {
    maxWidth: 360,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: 'rgba(255, 254, 252, 0.96)',
    borderWidth: 1,
    borderColor: '#dbe7fb',
    shadowColor: '#1f55ab',
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 5,
  },
  celebrationToastChapter: {
    backgroundColor: '#fff7f4',
    borderColor: '#f0c2bb',
  },
  celebrationToastIcon: {
    width: 36,
    height: 36,
    borderRadius: 999,
    backgroundColor: '#eef5ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  celebrationToastIconChapter: {
    backgroundColor: '#ffe4de',
  },
  celebrationToastIconText: {
    fontSize: 18,
  },
  celebrationText: {
    flex: 1,
    gap: 3,
  },
  celebrationTitle: {
    color: '#173f7b',
    fontSize: 15,
    fontFamily: FONT_SANS_BOLD,
  },
  celebrationBody: {
    color: '#5c7390',
    fontSize: 12,
    lineHeight: 17,
    fontFamily: FONT_SANS,
  },
  loadingScreen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#fffdf9',
  },
  loadingTitle: {
    color: '#173f7b',
    fontSize: 28,
    fontFamily: FONT_SERIF,
  },
  loadingText: {
    color: '#6a809f',
    fontSize: 15,
    fontFamily: FONT_SANS,
  },
  errorText: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 18,
    color: '#cf4339',
    textAlign: 'center',
  },
  articleSafeArea: {
    flex: 1,
    backgroundColor: '#fffdf9',
  },
  articleHeader: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e7edf8',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  articleHeaderRule: {
    width: 54,
    height: 3,
    backgroundColor: '#2d66c2',
    marginBottom: 14,
  },
  articleEyebrow: {
    color: '#cf5a47',
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontFamily: FONT_SANS_BOLD,
  },
  articleTitle: {
    marginTop: 6,
    color: '#173f7b',
    fontSize: 31,
    lineHeight: 37,
    maxWidth: 280,
    fontFamily: FONT_SERIF,
    letterSpacing: -0.5,
  },
  articleScroll: {
    flex: 1,
  },
  articleContent: {
    paddingHorizontal: 24,
    paddingTop: 22,
    paddingBottom: 36,
    gap: 18,
  },
  articleLead: {
    color: '#2a4f84',
    fontSize: 20,
    lineHeight: 31,
    fontFamily: FONT_SERIF,
  },
  articleParagraph: {
    color: '#586f8c',
    fontSize: 17,
    lineHeight: 30,
    fontFamily: FONT_SANS,
  },
  articleCallout: {
    padding: 18,
    backgroundColor: '#fbfcfe',
    borderLeftWidth: 4,
    borderLeftColor: '#e85b4f',
  },
  articleCalloutLabel: {
    color: '#cf5a47',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontWeight: '700',
  },
  articleCalloutText: {
    marginTop: 10,
    color: '#54708f',
    fontSize: 16,
    lineHeight: 26,
    fontFamily: FONT_SANS,
  },
});
